#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Set up Node Version Manager
# export NVM_DIR="$HOME/.nvm"                            # You can change this if you want.
# export NVM_SOURCE="/usr/share/nvm"                     # The AUR package installs it to here.
# [ -s "$NVM_SOURCE/nvm.sh" ] && . "$NVM_SOURCE/nvm.sh"  # Load NVM

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
